### PR TITLE
Big code refactor

### PR DESCRIPTION
**Pull request by fernandomema**

### CODE REVIEW

**Comment by WilliamAcosta1** [comment]
Translation does not apply correctly:

image

**Comment by fernandomema** [comment]
> Translation does not apply correctly:
> 
> image

Fixed!
image

**Comment by WilliamAcosta1** [comment]
At the moment the translation is working correctly, it would only be to remove the annoying log from the console as it is spamming a lot.
image

**Review by WilliamAcosta1 — APPROVED** [review]
Everything works correctly as required

**Comment by fernandomema** [comment]
> At the moment the translation is working correctly, it would only be to remove the annoying log from the console as it is spamming a lot. image

Deleted.
Maybe in the future we can implement log levels

**Pull request merged**
